# Generated by Django 5.0.1 on 2024-01-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.SmallIntegerField(verbose_name='Цена Тура'),
        ),
    ]
