# Generated by Django 5.0.1 on 2024-01-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='descriptions',
            new_name='description',
        ),
    ]
